-- Create database
CREATE DATABASE `traffic_data_us` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

-- Create table
CREATE TABLE `chicago_traffic_crashes` (
  `CRASH_RECORD_ID` varchar(250) DEFAULT NULL,
  `CRASH_DATE` varchar(200) DEFAULT NULL,
  `POSTED_SPEED_LIMIT` bigint DEFAULT NULL,
  `TRAFFIC_CONTROL_DEVICE` varchar(200) DEFAULT NULL,
  `WEATHER_CONDITION` varchar(100) DEFAULT NULL,
  `LIGHTING_CONDITION` varchar(100) DEFAULT NULL,
  `FIRST_CRASH_TYPE` varchar(100) DEFAULT NULL,
  `TRAFFICWAY_TYPE` varchar(100) DEFAULT NULL,
  `PRIM_CONTRIBUTORY_CAUSE` varchar(255) DEFAULT NULL,
  `SEC_CONTRIBUTORY_CAUSE` varchar(255) DEFAULT NULL,
  `INJURIES_FATAL` double DEFAULT NULL,
  `INJURIES_INCAPACITATING` double DEFAULT NULL,
  `INJURIES_NON_INCAPACITATING` double DEFAULT NULL,
  `INJURIES_TOTAL` double DEFAULT NULL,
  `CRASH_HOUR` bigint DEFAULT NULL,
  `CRASH_DAY_OF_WEEK` bigint DEFAULT NULL,
  `CRASH_MONTH` bigint DEFAULT NULL,
  `BEAT_OF_OCCURRENCE` double DEFAULT NULL,
  `STREET_NAME` varchar(255) DEFAULT NULL,
  `LATITUDE` double DEFAULT NULL,
  `LONGITUDE` double DEFAULT NULL,
  `DATE_POLICE_NOTIFIED` varchar(200) DEFAULT NULL,
  `YEAR` varchar(4) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;